### PR TITLE
[FIX] README false variable name

### PR DESCRIPTION
**Pull request by Kariton**
inside role rsyslog `logging_purge_original_conf` variable is named `logging_purge_confs`

### CODE REVIEW

**Review by spetrosi — APPROVED** [review]
Thanks for the PR, lgtm

**Comment by nhosoi** [comment]
Well, I'd think we should discuss about this...
The parameter name is already public for a while and changing it might be a problem (although there was no effect by setting it.) If ok, I'd rather change the source code as proposed in this pr against your pr/234.
https://github.com/Kariton/logging/pull/3

@spetrosi, @richm, what do you think? The downstream doc does not mention `logging_purge_original_conf`, but README.md does. It's available in galaxy and automation hub...

**Comment by richm** [comment]
> Well, I'd think we should discuss about this...
> The parameter name is already public for a while and changing it might be a problem (although there was no effect by setting it.) If ok, I'd rather change the source code as proposed in this pr against your pr/234.
> [Kariton#3](https://github.com/Kariton/logging/pull/3)
> 
> @spetrosi, @richm, what do you think? The downstream doc does not mention `logging_purge_original_conf`, but README.md does. It's available in galaxy and automation hub...

I think we should update the README.md to have the correct parameter name.  I do not think we should change the code to rename `logging_purge_confs` to be `logging_purge_original_conf` as that would be a breaking API change.  If a user figured out how to use `logging_purge_confs` despite the incorrect documentation, they will be unhappy that we have changed the parameter out from under them.

**Review by nhosoi — APPROVED** [review]
Thanks for your comments, @richm.
lgtm

**Pull request merged**
