### PR TITLE
Getting rid of cleanup.yml

### PR DESCRIPTION
**Pull request by nhosoi**
There is no use case for cleanup. Besides, it's implemented only for
the input tasks, not for the output tasks.

### CODE REVIEW

**Comment by nhosoi** [comment]
Thank you, @richm. Merging.

**Comment by pcahyna** [comment]
Where do you handle `state: absent` ?

**Comment by richm** [comment]
> Where do you handle `state: absent` ?

It isn't handled - let's do this in a separate PR

**Comment by nhosoi** [comment]
> > Where do you handle `state: absent` ?
> 
> It isn't handled - let's do this in a separate PR

Right. These cleanup.yml tasks were blindly deleting input files regardless of the flow relationships. We need to delete files assuring the healthy configuration... Opening a new RHELPLAN/PR.

**Comment by pcahyna** [comment]
As it was an interface change (the `absent` value for `state` ceased to be supported), it would have been better to mention it more prominently in the PR description.

**Comment by nhosoi** [comment]
> As it was an interface change (the `absent` value for `state` ceased to be supported), it would have been better to mention it more prominently in the PR description.

Sorry. This will be replaced with a new code. At that time, I'll emphasize it.

**Pull request merged**
