### PR TITLE
Use the openssl command-line interface instead of the openssl module

### PR DESCRIPTION
**Pull request by nhosoi**
in the test helper task tests/tasks/create_tests_certs.yml.

This is to avoid using the non ansible-core module.

### CODE REVIEW

**Comment by richm** [comment]
please rebase on top of the latest master to clear up the tox tests

**Comment by ukulekek** [comment]
[citest pending]

**Review by richm — APPROVED** [review]
lgtm

**Comment by nhosoi** [comment]
Thank you for reviewing the commit, @richm !

**Pull request merged**
