### PR TITLE
RHELPLAN-45641 - All system roles should use consistent parameter/key names for TLS parameters

### PR DESCRIPTION
**Pull request by nhosoi**
- Complying with the consistent tls parameter/key names:
```
    logging_pki_files:
      - ca_cert_src:     ca cert path on the control host
        cert_src:        cert path on the control host
        private_key_src: key path on the control host
        ca_cert:     ca cert path on the managed host
        cert:        cert path on the managed host
        private_key: key path on the managed host
```
- Updated README.md with better parameter grouping
- In the copy task in tasks/main.yml, which copies the src files to the dest,
  added a check whether triplets are given or not.
- Adding a test playbook tests_basics_forwards_cert_missing.yml.
- Put the debug code into a block which is needed by the new test which runs
  the second logging role for the recovery from the first failure.

- Complying with the consistent tls parameter/key names in the elasticsearch output.
  Replacing key param with private_key.

### CODE REVIEW

**Comment by nhosoi** [comment]
@richm, the standard tls parameters might be changed more, but I think this pr makes the further change easier...

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
@richm, @pcahyna, could you please help me? I don't know why but it started failing with SELinux error although this pr is not changing anything related to it (I believe...)
systemctl shows this permission denied error.
```
# systemctl status rsyslog -l
<<ship>>
Jul 02 02:05:08 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com systemd[1]: Started System Logging Service.
Jul 02 02:05:08 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com rsyslogd[15841]: imjournal: journal files changed, reloading...  [v8.1911.0-3.el8 try https://www.rsyslog.com/e/0 ]
Jul 02 02:05:13 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com rsyslogd[15841]: imfile: poll_tree cannot stat file '/var/log/inputdirectory/test.log' - ignored: Permission denied [v8.1911.0-3.el8]
```
Here's part of the output from sealert...
```
# sealert -l d6b7579a-52d5-456b-b803-6ad49a5ff6c7
<<snip>>
SELinux is preventing /usr/sbin/rsyslogd from getattr access on the file /var/log/inputdirectory/test.log.
*****  Plugin restorecon (99.5 confidence) suggests   ************************
If you want to fix the label.
/var/log/inputdirectory/test.log default label should be var_log_t.
Then you can run restorecon. The access attempt may have been stopped due to insufficient permissions to access a parent directory in which case try to change the following command accordingly.
Do
# /sbin/restorecon -v /var/log/inputdirectory/test.log
<<snip>>
Raw Audit Messages
type=AVC msg=audit(1593655514.571:1758): avc:  denied  { getattr } for  pid=15841 comm="in:imfile" path="/var/log/inputdirectory/test.log" dev="vda1" ino=13039806 scontext=system_u:system_r:syslogd_t:s0 tcontext=unconfined_u:object_r:admin_home_t:s0 tclass=file permissive=0
```
It suggests to fix the label to var_log_t, but it looks to me the file already has the correct label.
```
# ls -ldZ /var/log /var/log/inputdirectory/ /var/log/inputdirectory/*.log
drwx------. 10 root root system_u:object_r:var_log_t:s0     4096 Jul  2 02:04 /var/log
drwx------.  2 root root unconfined_u:object_r:var_log_t:s0   22 Jul  2 02:05 /var/log/inputdirectory/
-rw-r--r--.  1 root root system_u:object_r:var_log_t:s0      114 Jul  2 02:05 /var/log/inputdirectory/test.log
```
I'm trying to gather any useful information for troubleshooting, but so far I cannot find any clue...
```
# matchpathcon /var/log/inputdirectory
/var/log/inputdirectory	system_u:object_r:var_log_t:s0
# matchpathcon -V /var/log/inputdirectory
/var/log/inputdirectory verified.
# matchpathcon -V /var/log/inputdirectory/*
/var/log/inputdirectory/test.log verified.
```
Do you have any idea why it started failing? Thanks...

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by richm** [comment]
> Do you have any idea why it started failing? Thanks...

No - what platform is this?  Fedora 32?  If you restart rsyslogd after confirming that the directory is labeled correctly, does it startup without the selinux error?  If you run selinux in Permissive mode, does it work, and do you get the alert in /var/log/audit/audit.log?  Maybe ask @jvymazal - are you aware of any selinux policy changes related to rsyslog?

**Comment by nhosoi** [comment]
> > Do you have any idea why it started failing? Thanks...
> 
> No - what platform is this? Fedora 32? If you restart rsyslogd after confirming that the directory is labeled correctly, does it startup without the selinux error? If you run selinux in Permissive mode, does it work, and do you get the alert in /var/log/audit/audit.log? Maybe ask @jvymazal - are you aware of any selinux policy changes related to rsyslog?

Actually, it happens on rhel-8. I found the failures in this pr and I ran it on my laptop. This [comment](https://github.com/linux-system-roles/logging/pull/146#issuecomment-652776670) is reproduced result on it. More strangely, it sometimes passes, but not all the time. You might have noticed that I put [citest bad] many times. One of them made linux-system-roles-test/rhel-8 — linux-system-roles-42-c5h4s@2020-07-02 02:05:57.904469 passed. But still rhel-x has not (please ignore this fedora32 failure, it is an rpm repo issue).

Regarding the AVCs in audit.log, here they are...
```
type=AVC msg=audit(1593721053.128:1753): avc:  denied  { read } for  pid=15906 comm="in:imfile" name="test.log" dev="vda1" ino=9271853 scontext=system_u:system_r:syslogd_t:s0 tcontext=unconfined_u:object_r:admin_home_t:s0 tclass=file permissive=1
type=AVC msg=audit(1593721053.128:1753): avc:  denied  { open } for  pid=15906 comm="in:imfile" path="/var/log/inputdirectory/test.log" dev="vda1" ino=9271853 scontext=system_u:system_r:syslogd_t:s0 tcontext=unconfined_u:object_r:admin_home_t:s0 tclass=file permissive=1
type=SYSCALL msg=audit(1593721053.128:1753): arch=c000003e syscall=257 success=yes exit=8 a0=ffffff9c a1=7f5744000da0 a2=80000 a3=0 items=0 ppid=1 pid=15906 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="in:imfile" exe="/usr/sbin/rsyslogd" subj=system_u:system_r:syslogd_t:s0 key=(null)^]ARCH=x86_64 SYSCALL=openat AUID="unset" UID="root" GID="root" EUID="root" SUID="root" FSUID="root" EGID="root" SGID="root" FSGID="root"
type=PROCTITLE msg=audit(1593721053.128:1753): proctitle=2F7573722F7362696E2F727379736C6F6764002D6E
type=AVC msg=audit(1593721053.128:1754): avc:  denied  { ioctl } for  pid=15906 comm="in:imfile" path="/var/log/inputdirectory/test.log" dev="vda1" ino=9271853 ioctlcmd=0x5401 scontext=system_u:system_r:syslogd_t:s0 tcontext=unconfined_u:object_r:admin_home_t:s0 tclass=file permissive=1
```
Again, /var/log/inputdirectory/test.log has var_log_t context.
```
-rw-r--r--. 1 root root system_u:object_r:var_log_t:s0     114 Jul  2 20:17 /var/log/inputdirectory/test.log
/var/log/inputdirectory/:
total 4
-rw-r--r--. 1 root root system_u:object_r:var_log_t:s0 114 Jul  2 20:17 test.log
```

**Comment by jvymazal** [comment]
Unfortunately I do not know of selinux errors of this type. There are multiple known problems of selinux denial on upper levels of file tree due to the way newer version of imfile module are accessing the file-system however this does not look like the case, /var/log should be permitted under standard policy for rsyslog.

**Comment by nhosoi** [comment]
> Unfortunately I do not know of selinux errors of this type. There are multiple known problems of selinux denial on upper levels of file tree due to the way newer version of imfile module are accessing the file-system however this does not look like the case, /var/log should be permitted under standard policy for rsyslog.

Thanks, @jvymazal. I investigated this issue some more and concluded this is an unfortunate case of the combination of inotify and SELinux behaviour of the ansible copy module.

First of all, my test cases had an insufficient checking which covered up this failure. It's likely the cover-up was removed by some timing change and this issue was revealed... I'm going to submit a PR including the check fix.

Here are my observations.
In the test playbook (tests_combination.yml), I deployed and started rsyslog with imfile enabled, then generated an input log file for the imfile using the ansible copy module. More specifically like this. This causes the SELinux failure [0] and imfile issues an error [1].
```
    - name: Create a test log file in {{ __test_inputfiles_dir }}
      copy:
        dest: "{{ __test_inputfiles_dir }}/test.log"
        content: "# log file for rsyslog testing\n"
      changed_when: false

    - name: Add a fake log message to {{ __test_inputfiles_dir }}/test.log
      lineinfile:
        path: "{{ __test_inputfiles_dir }}/test.log"
        line: "<167>Mar 20 01:00:00 11.22.33.44 tag msgnum:00000000:26:abcdefghijklmnopqrstuvwxyz"
```
After the test failed, I checked the test.log context on the managed host, which looks correct [2] and rsyslog imfile should be able to read the file, but it cannot.

BTW, I even added `setype: var_log_t` to the copy task, but it did not help to solve AVC [0].
```
       copy:
         dest: "{{ __test_inputfiles_dir }}/test.log"
         content: "# log file for rsyslog testing\n"
+        setype: var_log_t
       changed_when: false
```
I was so confused and searched old issues in the ansible and ran into [this one](https://github.com/ansible/ansible/issues/3412), which says copy copies a local file to /root on the targeted host then moves it to the final destination.

From here, it is just my theory, but ansible copy copies test.log to /root once, where the setype is set to admin_home_t. Then, it moves to /var/log/inputdirectory. After it's moved, it sets to the expected selinux type var_log_t, I'd think. And sadly, inotify gets notified when test.log is moved to /var/log/inputdirectory, at that time the setype is still admin_home_t. And the mismatch cannot be fixed for inotify unless rsyslogd is restarted or other source of the notifications such as creating another file in /var/log/inputdirectory.

Another reasoning is instead of using the copy module, using the shell module to create the same test.log input file works around the problem... So, for now I'm going to change the test to use the workaround...

[0] - type=AVC msg=audit(1593910277.717:1717): avc:  denied  { getattr } for  pid=15818 comm="in:imfile" path="/var/log/inputdirectory/test.log" dev="vda1" ino=135325 scontext=system_u:system_r:syslogd_t:s0 tcontext=unconfined_u:object_r:admin_home_t:s0 tclass=file permissive=0
[1] - rsyslogd[15836]: imfile: poll_tree cannot stat file '/var/log/inputdirectory/test.log' - ignored: Permission denied [v8.1911.0-3.el8]
[2] - -rw-r--r--. 1 root root system_u:object_r:var_log_t:s0 114 Jul  5 00:51 /var/log/inputdirectory/test.log

**Comment by nhosoi** [comment]
I opened a PR for fixing the CI tests.
https://github.com/linux-system-roles/logging/pull/149

**Comment by nhosoi** [comment]
@jvymazal, I quickly checked the imfile code. It does not watch IN_ATTRIB. I.e., it won't be notified if the mode of the file is updated? (SELinux context change does not look included in the list IN_ATTRIB covers, though...) But for instance, a simple access mode or ownership change would not be notified to imfile?

**Comment by nhosoi** [comment]
[citest bad]

**Comment by richm** [comment]
> BTW, I even added setype: var_log_t to the copy task, but it did not help to solve AVC [0].

That sounds like a bug in the copy module, unless there is simply no way to rename/move a file and relabel it in one atomic operation.

>  I guess SELinux type change is a corner case and if inotify does not handle the SELinux related updates, there's no benefit to watch IN_ATTRIB.

Correct.

**Comment by nhosoi** [comment]
Thank you, @richm. Merging.

**Pull request merged**
