### PR TITLE
meta/main.yml: CI - add support for Fedora 33

### PR DESCRIPTION
**Pull request by jharuda**
Signed-off-by: Jakub Haruda <jharuda@redhat.com>

### CODE REVIEW

**Review by richm — APPROVED** [review]
lgtm

**Comment by nhosoi** [comment]
> lgtm

+1
I'm curious. Why centos-6 and rhel-6 are successful now? It's skipping the tests with success? > @jharuda, @richm?

**Comment by richm** [comment]
yes - there is no github status for skipped, so we're marking them as success

**Comment by nhosoi** [comment]
> yes - there is no github status for skipped, so we're marking them as success

Great! We have less noise now. :)

Merging this pr.

**Pull request merged**
