### PR TITLE
WIP: tox-lsr wip

### PR DESCRIPTION
**Pull request by richm**
testing tox-lsr plugin

### CODE REVIEW

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
I have also verified that the plugin works with logging https://github.com/linux-system-roles/logging/pull/187/ and with certificate https://github.com/linux-system-roles/certificate/pull/69

I don't really want to proceed any further until we can come to a consensus that this is the right approach.

**Review by nhosoi — CHANGES_REQUESTED** [review]
lgtm

@richm, I ran `tox` manually following the README https://github.com/linux-system-roles/tox-lsr/ and verified there's no errors. Since travis-CI does not run anyway, can we merge this pr?

**Comment by richm** [comment]
> @richm, I ran `tox` manually following the README https://github.com/linux-system-roles/tox-lsr/ and verified there's no errors. Since travis-CI does not run anyway, can we merge this pr?

I think I will delete it, and instead focus on replacing travis ci with github actions, then go back to tox-lsr.

**Pull request closed without merging**
