### PR TITLE
[WIP] Support elasticsearch certs deployment

### PR DESCRIPTION
**Pull request by nhosoi**
rsyslog: Supporting local paths of ca_cert, cert and key for the elasticsearch to be deployed to the remote host.
Adding use_local_omelasticsearch_cert.
Adding the suggestion from @sradco to "Collect local viaq cert files" task.

### CODE REVIEW

**Comment by sradco** [comment]
Should it be either take files from local, which means user states ca_src, cert_src and key_src OR take them from the /etc/rsyslog.d/viaq/ directory and then user states ca, cert and key?

I see that in this patch we take both and documentation is not clear..

@richm @nhosoi

**Comment by richm** [comment]
> I think this should be per elasticsearch. So potentially, you can send to 1 elasticsearch with cert auth and to another without. Does that make sense?

yes
or to have a different cert/key for each elasticsearch

**Comment by richm** [comment]
> I updated your patch in my PR
> https://github.com/linux-system-roles/logging/pull/27/files#diff-659e5a90bded4fec488b5097947f94e5
> I believe it works now as expected. Please review.
> 
> But I have a question, Shouldn't we take the local files from ca_src, cert_src and key_src OR take them from form /etc/rsyslog.d/viaq/ directory + ca, cert and key?
> 
> I see that in this patch we take both and documentation is not clear..

We should take both but there should be a clear precedence - take take the local files from ca_src, cert_src and key_src if specified, or take them from form /etc/rsyslog.d/viaq/ directory + ca, cert and key

**Comment by sradco** [comment]
@nhosoi , I believe this can be abandoned since PR #27 added support for it.
Please test current master handles this currectly.

**Pull request closed without merging**
