### PR TITLE
Fixing "logging README.html examples are rendered incorrectly"

### PR DESCRIPTION
**Pull request by nhosoi**
As suggested, removed numbering and itemizing.

RHELPLAN-80116

### CODE REVIEW

**Comment by nhosoi** [comment]
logging_readme

**Review by richm — APPROVED** [review]
lgtm

**Comment by nhosoi** [comment]
There's another issue in rendering. Sadly, no links work in the rendered page even the ones inside the same readme file... Should we remove the links such as table of contents?

**Comment by richm** [comment]
> There's another issue in rendering. Sadly, no links work in the rendered page even the ones inside the same readme file... Should we remove the links such as table of contents?

yes, if there is no way to make them work

**Comment by nhosoi** [comment]
> > There's another issue in rendering. Sadly, no links work in the rendered page even the ones inside the same readme file... Should we remove the links such as table of contents?
> 
> yes, if there is no way to make them work

I found other collections in AH do not use the local links (#tag), while we do in these roles. The local links in these readme files do not work on AH. I'd think we should modify them all together just in the collection artifact for AH as the links are useful in /usr/share/doc/rhel-system-roles/*.
```
certificate/README.md
cockpit/README.md
ha_cluster/README.md
logging/README.md
network/README.md
storage/README.md
vpn/README.md
```
So, merging this pr for now.

**Pull request merged**
