### PR TITLE
Adding " - DO NOT EDIT" to the ansible_managed comment in each genera…

### PR DESCRIPTION
**Pull request by nhosoi**
…ted config file.

`  # Ansible managed - DO NOT EDIT`

### CODE REVIEW

**Comment by richm** [comment]
In linux system roles we don't use `{{ ansible_managed }}` very much, but in the places we use it, it is used like this:
`# {{ ansible_managed }}`
I'm not sure what the default text is - if it doesn't include "do not edit" then I think we should override this in the `defaults/main.yml`, rather than edit each file that is ansible managed and add text - @pcahyna ?

**Comment by nhosoi** [comment]
> In linux system roles we don't use `{{ ansible_managed }}` very much, but in the places we use it, it is used like this:
> `# {{ ansible_managed }}`
> I'm not sure what the default text is -

It is "Ansible managed".  The logging role has been putting the comment `# Ansible managed` by `# {{ ansible_managed }}`.

>  if it doesn't include "do not edit" then I think we should override this in the `defaults/main.yml`, rather than edit each file that is ansible managed and add text - @pcahyna ?

Ok.  Just fyi, I tried to directly override ansible_managed in defaults/main.yml as well as in roles/rsyslog/defaults/main.yml.  But it's cleaned up and only "Ansible managed" is printed.  I guess we cannot use ansible_managed, but we should define our own internal variable?  LIke __rsyslog_ansible_managed?

**Comment by richm** [comment]
>  LIke __rsyslog_ansible_managed?

I think we should not do anything about it for now.  Just leave it as `# {{ ansible_managed }}` and use the default text for now.  If it becomes a problem we can fix it later.  I also think we should solve this globally, for all system roles, if we need a solution.

**Comment by nhosoi** [comment]
There is no plan to put "DO NOT EDIT" to the configuration files generated by the linux-system-roles. Closing this pr for now.

**Pull request closed without merging**
