### PR TITLE
Add uid and pwd parameters

### PR DESCRIPTION
**Pull request by avlitman**
We want to expose the uid and pwd parameters in our role,
to allow basic auth on the elasticsearch server.

The metrics update can be seen here: https://gerrit.ovirt.org/#/c/ovirt-engine-metrics/+/116098/

Bug-Url: https://bugzilla.redhat.com/1990490

Signed-off-by: Aviv Litman <alitman@redhat.com>

### CODE REVIEW

**Comment by nhosoi** [comment]
Sorry, @avlitman. There was a yamllint error (line too long) in my proposal. Could you make this change in your commit?
```
diff --git a/roles/rsyslog/tasks/outputs/elasticsearch/main.yml b/roles/rsyslog/tasks/outputs/elasticsearch/main.yml
index b1a4473..6d92779 100644
--- a/roles/rsyslog/tasks/outputs/elasticsearch/main.yml
+++ b/roles/rsyslog/tasks/outputs/elasticsearch/main.yml
@@ -33,7 +33,8 @@
   when: (logging_elasticsearch_password is not defined) or
         (logging_elasticsearch_password | length == 0)
 
-- name: Create elasticsearch output configuration files in /etc/rsyslog.d (no_log)
+- name: "Create elasticsearch output configuration files in
+  /etc/rsyslog.d (no_log)"
   vars:
     __rsyslog_packages: []
     __rsyslog_rules:

```

**Comment by avlitman** [comment]
> Sorry, @avlitman. There was a yamllint error (line too long) in my proposal. Could you make this change in your commit?
> 
> ```
> diff --git a/roles/rsyslog/tasks/outputs/elasticsearch/main.yml b/roles/rsyslog/tasks/outputs/elasticsearch/main.yml
> index b1a4473..6d92779 100644
> --- a/roles/rsyslog/tasks/outputs/elasticsearch/main.yml
> +++ b/roles/rsyslog/tasks/outputs/elasticsearch/main.yml
> @@ -33,7 +33,8 @@
>    when: (logging_elasticsearch_password is not defined) or
>          (logging_elasticsearch_password | length == 0)
>  
> -- name: Create elasticsearch output configuration files in /etc/rsyslog.d (no_log)
> +- name: "Create elasticsearch output configuration files in
> +  /etc/rsyslog.d (no_log)"
>    vars:
>      __rsyslog_packages: []
>      __rsyslog_rules:
> ```

Done!
and ci tests passed.

Thank you

**Comment by nhosoi** [comment]
[citest]

**Review by nhosoi — APPROVED** [review]
lgtm

**Comment by richm** [comment]
> @richm, due to some github issue, we switched #236 to this pr #246. It has passed 4 tox tests and now is running the rest of the tests. Although it hasn't finished all the platforms, they actually passed in #236, where tox was failing. Do you think it's ok to merge this pr?

yes

**Pull request merged**
