### PR TITLE
[README] Support oVirt input + elasticsearch output

### PR DESCRIPTION
**Pull request by nhosoi**
Recovering the oVirt options section in README.md.

### CODE REVIEW

**Review by richm — APPROVED** [review]
lgtm

**Comment by nhosoi** [comment]
Thank you for reviewing this pr, @richm. Merged.

**Review by santos1709 — COMMENTED** [review]
lgtm as well!

**Comment by nhosoi** [comment]
> lgtm as well!

Thank you for your review, @santos1709 !!

**Pull request merged**
