### PR TITLE
Adding an rsyslog service error check to the CI tests.

### PR DESCRIPTION
**Pull request by nhosoi**

### CODE REVIEW

**Comment by pcahyna** [comment]
Why to use `grep` when Ansible provides a way to check what was in the output? https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#controlling-what-defines-failure
`'SOMETHING' in command_result.stdout`
One then can avoid pipelines completely and use `command` instead of `shell` which is better anyway.

**Comment by pcahyna** [comment]
Are you sure you want to use stderr if the previous grep was using stdout? Also doesn't systemctl return a useful exit code that you can use without checking anything in the output?

**Comment by richm** [comment]
> Are you sure you want to use stderr if the previous grep was using stdout? Also doesn't systemctl return a useful exit code that you can use without checking anything in the output?

Right.  
```
$ sudo systemctl status tpm2-abrmd 
● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
   Loaded: loaded (/usr/lib/systemd/system/tpm2-abrmd.service; disabled; vendor>
   Active: failed (Result: exit-code) since Sun 2020-05-10 18:48:46 MDT; 1 day >
  Process: 6482 ExecStart=/usr/sbin/tpm2-abrmd (code=exited, status=69)
...
$ echo $?
3
```
and there is no output to stderr:
```
$ sudo systemctl status tpm2-abrmd > /dev/null
empty
```

**Comment by pcahyna** [comment]
it would be helpful to see the exact error that @nhosoi is actually checking for and whether it is really analogous to the example shown by @richm . (Maybe the intent was to catch a different kind of error, but without more explanation it is hard to tell.)

**Comment by nhosoi** [comment]
I want to check this type of errors. The server is up but not fully functioning. In such a case, systemctl status returns 0. (please note that this No such file error for the certs is a known issue for now.)
```
systemctl status rsyslog --no-pager
● rsyslog.service - System Logging Service
   Loaded: loaded (/usr/lib/systemd/system/rsyslog.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-05-12 22:24:34 UTC; 9min ago
     Docs: man:rsyslogd(8)
           https://www.rsyslog.com/doc/
 Main PID: 17326 (rsyslogd)
    Tasks: 9 (limit: 11508)
   Memory: 4.6M
   CGroup: /system.slice/rsyslog.service
           └─17326 /usr/sbin/rsyslogd -n

May 12 22:24:34 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com systemd[1]: Started System Logging Service.
May 12 22:24:34 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com rsyslogd[17326]: error: 'tls.cacert' file /etc/rsyslog.d/es-ca.crt couldn't be accessed: No such file or directory  [v8.1911.0-3.el8 try https://www.rsyslog.com/e/2039 ]
May 12 22:24:34 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com rsyslogd[17326]: error: 'tls.mycert' file /etc/rsyslog.d/es-cert.pem couldn't be accessed: No such file or directory  [v8.1911.0-3.el8 try https://www.rsyslog.com/e/2039 ]
May 12 22:24:34 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com rsyslogd[17326]: error: 'tls.myprivkey' file /etc/rsyslog.d/es-key.pem couldn't be accessed: No such file or directory  [v8.1911.0-3.el8 try https://www.rsyslog.com/e/2039 ]
May 12 22:24:34 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com rsyslogd[17326]: error: 'tls.cacert' file /etc/rsyslog.d/es-ca.crt couldn't be accessed: No such file or directory  [v8.1911.0-3.el8 try https://www.rsyslog.com/e/2039 ]
May 12 22:24:34 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com rsyslogd[17326]: error: 'tls.mycert' file /etc/rsyslog.d/es-cert.pem couldn't be accessed: No such file or directory  [v8.1911.0-3.el8 try https://www.rsyslog.com/e/2039 ]
May 12 22:24:34 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com rsyslogd[17326]: error: 'tls.myprivkey' file /etc/rsyslog.d/es-key.pem couldn't be accessed: No such file or directory  [v8.1911.0-3.el8 try https://www.rsyslog.com/e/2039 ]
May 12 22:24:34 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com rsyslogd[17326]: imfile: on startup file '/var/log/ovirt-engine/engine.log' does not exist but is configured in static file monitor - this may indicate a miscon…v8.1911.0-3.el8]
May 12 22:24:34 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com rsyslogd[17326]: [origin software="rsyslogd" swVersion="8.1911.0-3.el8" x-pid="17326" x-info="https://www.rsyslog.com"] start
May 12 22:24:34 ibm-p8-kvm-03-guest-02.virt.pnr.lab.eng.rdu2.redhat.com rsyslogd[17326]: imjournal: journal files changed, reloading...  [v8.1911.0-3.el8 try https://www.rsyslog.com/e/0 ]
Hint: Some lines were ellipsized, use -l to show in full.
[root@ibm-p8-kvm-03-guest-02 ~]# echo $?
0
```
And yes, I should have checked stdout... Thanks for finding it out.
```
[root@ibm-p8-kvm-03-guest-02 ~]# systemctl status rsyslog --no-pager > /tmp/out 2> /tmp/err
[root@ibm-p8-kvm-03-guest-02 ~]# ls -l /tmp/{out,err}
-rw-r--r--. 1 root root    0 May 12 22:35 /tmp/err
-rw-r--r--. 1 root root 2772 May 12 22:35 /tmp/out
```

**Comment by pcahyna** [comment]
@nhosoi with this explanation it makes more sense, thanks. Let's hope that rsyslog never prints anything like "no errors detected". Can you please briefly explain this strategy in a comment in the code, because it is not obvious now without seeing this discussion? Also I suspect that you should check for the return code from systemctl as well, since if it is nonzero, it also indicates some problem.

**Comment by richm** [comment]
lgtm

**Comment by nhosoi** [comment]
Thanks for reviewing this PR, @richm and @pcahyna. Merging...

**Pull request merged**
